# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 12:52
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_cours', models.BooleanField()),
                ('facture', models.BooleanField()),
                ('annulee', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=django.contrib.auth.models.User)),
                ('id_archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturier.Archive')),
                ('id_devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturier.Devis')),
            ],
        ),
        migrations.AddField(
            model_name='archive',
            name='id_devis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturier.Devis'),
        ),
        migrations.AddField(
            model_name='archive',
            name='id_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturier.Username'),
        ),
    ]
