# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='username',
            name='id_archive',
        ),
        migrations.RemoveField(
            model_name='username',
            name='id_devis',
        ),
        migrations.RenameField(
            model_name='archive',
            old_name='id_devis',
            new_name='devis',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='id_username',
        ),
        migrations.AddField(
            model_name='devis',
            name='statut',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facturier.Statut'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statut',
            name='annulee',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='statut',
            name='en_cours',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='statut',
            name='facture',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Username',
        ),
        migrations.AddField(
            model_name='user',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='facturier.Archive'),
        ),
        migrations.AddField(
            model_name='user',
            name='devis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturier.Devis'),
        ),
        migrations.AddField(
            model_name='archive',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='username', to='facturier.User'),
            preserve_default=False,
        ),
    ]
